// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.4
// source: booking/booking.proto

package booking

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ListingId     string                 `protobuf:"bytes,2,opt,name=listing_id,json=listingId,proto3" json:"listing_id,omitempty"`
	StartDate     string                 `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"` // ISO string
	EndDate       string                 `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	DurationType  string                 `protobuf:"bytes,5,opt,name=duration_type,json=durationType,proto3" json:"duration_type,omitempty"` // "hour", "day", or "month"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBookingRequest) Reset() {
	*x = CreateBookingRequest{}
	mi := &file_booking_booking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookingRequest) ProtoMessage() {}

func (x *CreateBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_booking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookingRequest.ProtoReflect.Descriptor instead.
func (*CreateBookingRequest) Descriptor() ([]byte, []int) {
	return file_booking_booking_proto_rawDescGZIP(), []int{0}
}

func (x *CreateBookingRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateBookingRequest) GetListingId() string {
	if x != nil {
		return x.ListingId
	}
	return ""
}

func (x *CreateBookingRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *CreateBookingRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *CreateBookingRequest) GetDurationType() string {
	if x != nil {
		return x.DurationType
	}
	return ""
}

type CancelBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelBookingRequest) Reset() {
	*x = CancelBookingRequest{}
	mi := &file_booking_booking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelBookingRequest) ProtoMessage() {}

func (x *CancelBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_booking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelBookingRequest.ProtoReflect.Descriptor instead.
func (*CancelBookingRequest) Descriptor() ([]byte, []int) {
	return file_booking_booking_proto_rawDescGZIP(), []int{1}
}

func (x *CancelBookingRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

type GetBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookingRequest) Reset() {
	*x = GetBookingRequest{}
	mi := &file_booking_booking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookingRequest) ProtoMessage() {}

func (x *GetBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_booking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookingRequest.ProtoReflect.Descriptor instead.
func (*GetBookingRequest) Descriptor() ([]byte, []int) {
	return file_booking_booking_proto_rawDescGZIP(), []int{2}
}

func (x *GetBookingRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

type ListBookingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBookingsRequest) Reset() {
	*x = ListBookingsRequest{}
	mi := &file_booking_booking_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBookingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBookingsRequest) ProtoMessage() {}

func (x *ListBookingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_booking_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBookingsRequest.ProtoReflect.Descriptor instead.
func (*ListBookingsRequest) Descriptor() ([]byte, []int) {
	return file_booking_booking_proto_rawDescGZIP(), []int{3}
}

func (x *ListBookingsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type BookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ListingId     string                 `protobuf:"bytes,3,opt,name=listing_id,json=listingId,proto3" json:"listing_id,omitempty"`
	StartDate     string                 `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	DurationType  string                 `protobuf:"bytes,6,opt,name=duration_type,json=durationType,proto3" json:"duration_type,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"` // "active", "cancelled"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookingResponse) Reset() {
	*x = BookingResponse{}
	mi := &file_booking_booking_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingResponse) ProtoMessage() {}

func (x *BookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booking_booking_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingResponse.ProtoReflect.Descriptor instead.
func (*BookingResponse) Descriptor() ([]byte, []int) {
	return file_booking_booking_proto_rawDescGZIP(), []int{4}
}

func (x *BookingResponse) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *BookingResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BookingResponse) GetListingId() string {
	if x != nil {
		return x.ListingId
	}
	return ""
}

func (x *BookingResponse) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *BookingResponse) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *BookingResponse) GetDurationType() string {
	if x != nil {
		return x.DurationType
	}
	return ""
}

func (x *BookingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListBookingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bookings      []*BookingResponse     `protobuf:"bytes,1,rep,name=bookings,proto3" json:"bookings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBookingsResponse) Reset() {
	*x = ListBookingsResponse{}
	mi := &file_booking_booking_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBookingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBookingsResponse) ProtoMessage() {}

func (x *ListBookingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booking_booking_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBookingsResponse.ProtoReflect.Descriptor instead.
func (*ListBookingsResponse) Descriptor() ([]byte, []int) {
	return file_booking_booking_proto_rawDescGZIP(), []int{5}
}

func (x *ListBookingsResponse) GetBookings() []*BookingResponse {
	if x != nil {
		return x.Bookings
	}
	return nil
}

var File_booking_booking_proto protoreflect.FileDescriptor

const file_booking_booking_proto_rawDesc = "" +
	"\n" +
	"\x15booking/booking.proto\x12\abooking\"\xad\x01\n" +
	"\x14CreateBookingRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"listing_id\x18\x02 \x01(\tR\tlistingId\x12\x1d\n" +
	"\n" +
	"start_date\x18\x03 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x04 \x01(\tR\aendDate\x12#\n" +
	"\rduration_type\x18\x05 \x01(\tR\fdurationType\"5\n" +
	"\x14CancelBookingRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\"2\n" +
	"\x11GetBookingRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\".\n" +
	"\x13ListBookingsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xdf\x01\n" +
	"\x0fBookingResponse\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"listing_id\x18\x03 \x01(\tR\tlistingId\x12\x1d\n" +
	"\n" +
	"start_date\x18\x04 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x05 \x01(\tR\aendDate\x12#\n" +
	"\rduration_type\x18\x06 \x01(\tR\fdurationType\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\"L\n" +
	"\x14ListBookingsResponse\x124\n" +
	"\bbookings\x18\x01 \x03(\v2\x18.booking.BookingResponseR\bbookings2\xc0\x02\n" +
	"\x0eBookingService\x12H\n" +
	"\rCreateBooking\x12\x1d.booking.CreateBookingRequest\x1a\x18.booking.BookingResponse\x12H\n" +
	"\rCancelBooking\x12\x1d.booking.CancelBookingRequest\x1a\x18.booking.BookingResponse\x12F\n" +
	"\x0eGetBookingById\x12\x1a.booking.GetBookingRequest\x1a\x18.booking.BookingResponse\x12R\n" +
	"\x13ListBookingsForUser\x12\x1c.booking.ListBookingsRequest\x1a\x1d.booking.ListBookingsResponseBaZ_github.com/fr1gn/bookingsystem/backend/gobooking/services/booking-service/proto/booking;bookingb\x06proto3"

var (
	file_booking_booking_proto_rawDescOnce sync.Once
	file_booking_booking_proto_rawDescData []byte
)

func file_booking_booking_proto_rawDescGZIP() []byte {
	file_booking_booking_proto_rawDescOnce.Do(func() {
		file_booking_booking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_booking_booking_proto_rawDesc), len(file_booking_booking_proto_rawDesc)))
	})
	return file_booking_booking_proto_rawDescData
}

var file_booking_booking_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_booking_booking_proto_goTypes = []any{
	(*CreateBookingRequest)(nil), // 0: booking.CreateBookingRequest
	(*CancelBookingRequest)(nil), // 1: booking.CancelBookingRequest
	(*GetBookingRequest)(nil),    // 2: booking.GetBookingRequest
	(*ListBookingsRequest)(nil),  // 3: booking.ListBookingsRequest
	(*BookingResponse)(nil),      // 4: booking.BookingResponse
	(*ListBookingsResponse)(nil), // 5: booking.ListBookingsResponse
}
var file_booking_booking_proto_depIdxs = []int32{
	4, // 0: booking.ListBookingsResponse.bookings:type_name -> booking.BookingResponse
	0, // 1: booking.BookingService.CreateBooking:input_type -> booking.CreateBookingRequest
	1, // 2: booking.BookingService.CancelBooking:input_type -> booking.CancelBookingRequest
	2, // 3: booking.BookingService.GetBookingById:input_type -> booking.GetBookingRequest
	3, // 4: booking.BookingService.ListBookingsForUser:input_type -> booking.ListBookingsRequest
	4, // 5: booking.BookingService.CreateBooking:output_type -> booking.BookingResponse
	4, // 6: booking.BookingService.CancelBooking:output_type -> booking.BookingResponse
	4, // 7: booking.BookingService.GetBookingById:output_type -> booking.BookingResponse
	5, // 8: booking.BookingService.ListBookingsForUser:output_type -> booking.ListBookingsResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_booking_booking_proto_init() }
func file_booking_booking_proto_init() {
	if File_booking_booking_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_booking_booking_proto_rawDesc), len(file_booking_booking_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_booking_booking_proto_goTypes,
		DependencyIndexes: file_booking_booking_proto_depIdxs,
		MessageInfos:      file_booking_booking_proto_msgTypes,
	}.Build()
	File_booking_booking_proto = out.File
	file_booking_booking_proto_goTypes = nil
	file_booking_booking_proto_depIdxs = nil
}
