// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.4
// source: listing/listing.proto

package listing

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateListingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	City          string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	OwnerId       string                 `protobuf:"bytes,5,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Category      string                 `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"` // example: "apartment", "studio", etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateListingRequest) Reset() {
	*x = CreateListingRequest{}
	mi := &file_listing_listing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateListingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateListingRequest) ProtoMessage() {}

func (x *CreateListingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_listing_listing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateListingRequest.ProtoReflect.Descriptor instead.
func (*CreateListingRequest) Descriptor() ([]byte, []int) {
	return file_listing_listing_proto_rawDescGZIP(), []int{0}
}

func (x *CreateListingRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateListingRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateListingRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *CreateListingRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateListingRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *CreateListingRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type GetListingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListingId     string                 `protobuf:"bytes,1,opt,name=listing_id,json=listingId,proto3" json:"listing_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListingRequest) Reset() {
	*x = GetListingRequest{}
	mi := &file_listing_listing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListingRequest) ProtoMessage() {}

func (x *GetListingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_listing_listing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListingRequest.ProtoReflect.Descriptor instead.
func (*GetListingRequest) Descriptor() ([]byte, []int) {
	return file_listing_listing_proto_rawDescGZIP(), []int{1}
}

func (x *GetListingRequest) GetListingId() string {
	if x != nil {
		return x.ListingId
	}
	return ""
}

type SearchListingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	City          string                 `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	MinPrice      float64                `protobuf:"fixed64,2,opt,name=min_price,json=minPrice,proto3" json:"min_price,omitempty"`
	MaxPrice      float64                `protobuf:"fixed64,3,opt,name=max_price,json=maxPrice,proto3" json:"max_price,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchListingsRequest) Reset() {
	*x = SearchListingsRequest{}
	mi := &file_listing_listing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchListingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchListingsRequest) ProtoMessage() {}

func (x *SearchListingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_listing_listing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchListingsRequest.ProtoReflect.Descriptor instead.
func (*SearchListingsRequest) Descriptor() ([]byte, []int) {
	return file_listing_listing_proto_rawDescGZIP(), []int{2}
}

func (x *SearchListingsRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *SearchListingsRequest) GetMinPrice() float64 {
	if x != nil {
		return x.MinPrice
	}
	return 0
}

func (x *SearchListingsRequest) GetMaxPrice() float64 {
	if x != nil {
		return x.MaxPrice
	}
	return 0
}

func (x *SearchListingsRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type ListingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	City          string                 `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	OwnerId       string                 `protobuf:"bytes,6,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Category      string                 `protobuf:"bytes,7,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListingResponse) Reset() {
	*x = ListingResponse{}
	mi := &file_listing_listing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListingResponse) ProtoMessage() {}

func (x *ListingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_listing_listing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListingResponse.ProtoReflect.Descriptor instead.
func (*ListingResponse) Descriptor() ([]byte, []int) {
	return file_listing_listing_proto_rawDescGZIP(), []int{3}
}

func (x *ListingResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ListingResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ListingResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ListingResponse) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *ListingResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ListingResponse) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *ListingResponse) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type SearchListingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Listings      []*ListingResponse     `protobuf:"bytes,1,rep,name=listings,proto3" json:"listings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchListingsResponse) Reset() {
	*x = SearchListingsResponse{}
	mi := &file_listing_listing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchListingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchListingsResponse) ProtoMessage() {}

func (x *SearchListingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_listing_listing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchListingsResponse.ProtoReflect.Descriptor instead.
func (*SearchListingsResponse) Descriptor() ([]byte, []int) {
	return file_listing_listing_proto_rawDescGZIP(), []int{4}
}

func (x *SearchListingsResponse) GetListings() []*ListingResponse {
	if x != nil {
		return x.Listings
	}
	return nil
}

var File_listing_listing_proto protoreflect.FileDescriptor

const file_listing_listing_proto_rawDesc = "" +
	"\n" +
	"\x15listing/listing.proto\x12\alisting\"\xaf\x01\n" +
	"\x14CreateListingRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04city\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x19\n" +
	"\bowner_id\x18\x05 \x01(\tR\aownerId\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\"2\n" +
	"\x11GetListingRequest\x12\x1d\n" +
	"\n" +
	"listing_id\x18\x01 \x01(\tR\tlistingId\"\x81\x01\n" +
	"\x15SearchListingsRequest\x12\x12\n" +
	"\x04city\x18\x01 \x01(\tR\x04city\x12\x1b\n" +
	"\tmin_price\x18\x02 \x01(\x01R\bminPrice\x12\x1b\n" +
	"\tmax_price\x18\x03 \x01(\x01R\bmaxPrice\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\"\xba\x01\n" +
	"\x0fListingResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04city\x18\x04 \x01(\tR\x04city\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12\x19\n" +
	"\bowner_id\x18\x06 \x01(\tR\aownerId\x12\x1a\n" +
	"\bcategory\x18\a \x01(\tR\bcategory\"N\n" +
	"\x16SearchListingsResponse\x124\n" +
	"\blistings\x18\x01 \x03(\v2\x18.listing.ListingResponseR\blistings2\xf5\x01\n" +
	"\x0eListingService\x12H\n" +
	"\rCreateListing\x12\x1d.listing.CreateListingRequest\x1a\x18.listing.ListingResponse\x12F\n" +
	"\x0eGetListingById\x12\x1a.listing.GetListingRequest\x1a\x18.listing.ListingResponse\x12Q\n" +
	"\x0eSearchListings\x12\x1e.listing.SearchListingsRequest\x1a\x1f.listing.SearchListingsResponseBaZ_github.com/fr1gn/bookingsystem/backend/gobooking/services/listing-service/proto/listing;listingb\x06proto3"

var (
	file_listing_listing_proto_rawDescOnce sync.Once
	file_listing_listing_proto_rawDescData []byte
)

func file_listing_listing_proto_rawDescGZIP() []byte {
	file_listing_listing_proto_rawDescOnce.Do(func() {
		file_listing_listing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_listing_listing_proto_rawDesc), len(file_listing_listing_proto_rawDesc)))
	})
	return file_listing_listing_proto_rawDescData
}

var file_listing_listing_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_listing_listing_proto_goTypes = []any{
	(*CreateListingRequest)(nil),   // 0: listing.CreateListingRequest
	(*GetListingRequest)(nil),      // 1: listing.GetListingRequest
	(*SearchListingsRequest)(nil),  // 2: listing.SearchListingsRequest
	(*ListingResponse)(nil),        // 3: listing.ListingResponse
	(*SearchListingsResponse)(nil), // 4: listing.SearchListingsResponse
}
var file_listing_listing_proto_depIdxs = []int32{
	3, // 0: listing.SearchListingsResponse.listings:type_name -> listing.ListingResponse
	0, // 1: listing.ListingService.CreateListing:input_type -> listing.CreateListingRequest
	1, // 2: listing.ListingService.GetListingById:input_type -> listing.GetListingRequest
	2, // 3: listing.ListingService.SearchListings:input_type -> listing.SearchListingsRequest
	3, // 4: listing.ListingService.CreateListing:output_type -> listing.ListingResponse
	3, // 5: listing.ListingService.GetListingById:output_type -> listing.ListingResponse
	4, // 6: listing.ListingService.SearchListings:output_type -> listing.SearchListingsResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_listing_listing_proto_init() }
func file_listing_listing_proto_init() {
	if File_listing_listing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_listing_listing_proto_rawDesc), len(file_listing_listing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_listing_listing_proto_goTypes,
		DependencyIndexes: file_listing_listing_proto_depIdxs,
		MessageInfos:      file_listing_listing_proto_msgTypes,
	}.Build()
	File_listing_listing_proto = out.File
	file_listing_listing_proto_goTypes = nil
	file_listing_listing_proto_depIdxs = nil
}
