version: '3.8'

services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7.0-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

  nats:
    image: nats:2.10-alpine
    restart: unless-stopped
    ports:
      - "4222:4222"

  auth-service:
    build:
      context: .
      dockerfile: services/auth-service/Dockerfile
    ports:
      - "50051:50051"
    depends_on:
      - mongo
      - redis
      - nats

  booking-service:
    build:
      context: .
      dockerfile: services/booking-service/Dockerfile
    ports:
      - "50052:50052"
    depends_on:
      - mongo
      - redis
      - nats

  listing-service:
    build:
      context: .
      dockerfile: services/listing-service/Dockerfile
    ports:
      - "50053:50053"
    depends_on:
      - mongo
      - redis
      - nats

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - booking-service
      - listing-service

volumes:
  mongo_data:
